### ISSUE TITLE
Build guide needed

### ISSUE THREAD

**Issue by WiGeeky** [HosseinShabani/pomodoro-app#2]
Since every package comes with a build guide, a build guide explaining how to build this (at least on one platform) is necessary. I'd do it but I don't have much experience with Electron.

**Comment by HosseinShabani** [comment]
You can run "dev" script. 
Eelctron config file just in first route index.js and other file are for svelte js

**Comment by WiGeeky** [comment]
I don't think that wraps it up, every legible package in GitHub follows a guideline explaining to people how to build/run the application, they're not expected to find such info in the issues.

I appreciate the project, so I might as well make a pull request about this.

**Comment by beigirad** [comment]
I agree with @WiGeeky. 
However, your developer apple account is also unidentified!

**Comment by WiGeeky** [comment]
@beigirad I'm no expert in Apple's ecosystem, judging by the content of this repo, I certainly believe someone with experience in that regard should work on it. I'm not sure about the owner of this repo but I'm collaborating with @amin3mej over at [his fork](https://github.com/amin3mej/pomodoro-app) as he's open to contributions.
Thank you for your attention!
